### ISSUE TITLE
How to import namespace of assembly built by .net 5.0.4

### ISSUE THREAD

**Issue by ingted** [pythonnet/clr-loader#10]
Excuse me, is it possible to import a namespace from an assembly built by .net 5.0.4?
I could execute these lines
```
import os
import sys
from clr_loader import get_coreclr
from pythonnet import set_runtime

runtime_config = os.path.join(r"Z:\SharFTrade\pythonnettest\pythonnettest\bin\Release\net5.0", "pythonnettest.runtimeconfig.json")
rt = get_coreclr(runtime_config)
set_runtime(rt)

import clr
```
without any errors, however I am unable to import namespace defined in the dll...

**Comment by filmor** [comment]
Please don't crosspost. This is not a support forum.

**Comment by ingted** [comment]
I am not ask for help.
It is a bug...

```
>>> clr.AddReference(System.AppDomain.CurrentDomain.GetAssemblies()[28].Location)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
   at System.Reflection.AssemblyName.nInit()
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Python.Runtime.AssemblyManager.LoadAssembly(String name) in Z:\SharFTrade\pythonnet\src\runtime\assemblymanager.cs:line 204
   at Python.Runtime.CLRModule.AddReference(String name) in Z:\SharFTrade\pythonnet\src\runtime\moduleobject.cs:line 480
>>>
```

With the same code, .net4.8 works fine.

**Comment by ingted** [comment]
An **ALREADY LOADED** assembly is unable to clr.AddReference?!
It is real a BUG.

**Comment by ingted** [comment]
In the first post, I missed the following code:

```
assembly_path = os.path.join(r"Z:\SharFTrade\pythonnettest\pythonnettest\bin\Release\net5.0", "pythonnettest.dll")
clr.AddReference(assembly_path)
```

There is no error.

**Comment by ingted** [comment]
But import doesn't work.
After I use reflection to load it successfully, import namespace is still unable to work.

**Comment by filmor** [comment]
1. Don't panic!
2. You are complaining on the wrong project
3. This is still not a support forum
4. Please provide a reproducible example and I'll try to have a look

**Comment by ingted** [comment]
Thanks again. And I am very sorry. It was all my fault.
[.dll should not be used](https://stackoverflow.com/questions/49998309/import-of-dll-with-pythonnet)

Will not bothering (create a support forum post... etc) again.
