### ISSUE TITLE
Learning to use clr-loader

### ISSUE THREAD

**Issue by matthias-github** [pythonnet/clr-loader#12]
I am learning to use clr-loader because my environment does not allow non-pure python libraries.

If I were using pythonnet I would something like:

```
>>> import clr
>>> clr.AddReference('System.Data')
<System.Reflection.RuntimeAssembly object at 0x00000229C0EC3288>
>>> from System.Data import DataTable
>>> DataTable()
<System.Data.DataTable object at 0x00000229C0EC3288>
```

What would be the equivalent in clr-loader?

FYI, my goal is to call the Server constructor of [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.server.-ctor?view=analysisservices-dotnet#microsoft-analysisservices-tabular-server-ctor).

**Comment by filmor** [comment]
`clr_loader` is extremely limited with regard to what you can call, pretty much exactly what is given in the [example](https://github.com/pythonnet/clr-loader/blob/master/example/TestClass.cs): A function with the signature `static int ...(IntPtr arg, int size)`

The .NET Core (or 5, 6, ...) hosting api is intentionally very limited. If you need more, please use Python.NET.
