### ISSUE TITLE
Source archive on PyPI to bring package to conda-forge

### ISSUE THREAD

**Issue by m-rossi** [pythonnet/clr-loader#18]
I just got notified you published the [first alpha of pythonnet 3.0](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.0-a1) and looked into what's necessary for the [conda-forge-recipe](https://github.com/conda-forge/pythonnet-feedstock) and saw `pythonnet` depends on this package.

In preparation for the 3.0 release I would also add this package to conda-forge. However to do that, it is required to have the source archive (`tar.gz`) including the license to PyPI. Could you add that?

**Comment by m-rossi** [comment]
...I just realized, the source archive just seems to be missing for the most recent version (0.1.7)

**Comment by filmor** [comment]
True, I forgot that, I'll upload the source archives for both clr-loader and pythonnet now. Thanks for the notice! :)

**Comment by m-rossi** [comment]
Thanks! I can also try to build the pre-releases with conda-forge.

**Comment by filmor** [comment]
Both are uploaded now. Beware that the build and runtime dependencies are simplified now. At build time on supported python versions (3.6-3.10), we only require a working .NET SDK >= v5 (though that is indeed required now), `wheel` and `setuptools`. Feel free to open issues against this or the pythonnet project.
