### ISSUE TITLE
Build issue when using dotnet-sdk v6

### ISSUE THREAD

**Issue by m-rossi** [pythonnet/clr-loader#19]
I just tested creating a recipe for conda-forge and seem to get some issues with dotnet-sdk v6: 

```
"System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USERNAME\miniforge3\conda-bld\clr_loader_1637417796354\_build_env\dotnet\sdk-manifests'
```

dotnet-sdk v5 seems to work fine. I tried to find out which dotnet-sdk is used in your github-actions, but failed. Which version you use?

If you are using v6 this may be related to the build process in the conda-forge-recipe: https://github.com/conda-forge/dotnet-feedstock

**Comment by filmor** [comment]
I have only been using v5 so far (that's the version that is available on gentoo). I will test v6 tomorrow.

**Comment by filmor** [comment]
I can't reproduce this on Linux. Both `clr-loader` and `pythonnet` build fine with .NET SDK v6.

**Comment by filmor** [comment]
Since the error happens in `dotnet` which we call directly just by name, I suggest verifying that indeed the correct binary is picked. It might be worth reporting this to the conda-forge recipe maintainers for dotnet as well.

**Comment by filmor** [comment]
Okay, last comment on this: I have found the issue and proposed a PR here https://github.com/conda-forge/dotnet-feedstock/pull/45. The "published" version of the .NET 6 SDK from conda-forge is simply broken as it misses a new directory.

**Comment by m-rossi** [comment]
> Okay, last comment on this: I have found the issue and proposed a PR here [conda-forge/dotnet-feedstock#45](https://github.com/conda-forge/dotnet-feedstock/pull/45). The "published" version of the .NET 6 SDK from conda-forge is simply broken as it misses a new directory.

Great, thank you! I will try with the new version once your PR is merged.
