### ISSUE TITLE
`clr_loader` should not by default shutdown runtime `at_exit`

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/clr-loader#26]
The caveats are:
- `AppDomain.ProcessExit` might not be called
- `AppDomain.DomainUnload` might not be called
- critical finalizers https://docs.microsoft.com/en-us/dotnet/api/system.runtime.constrainedexecution.criticalfinalizerobject?view=net-6.0

**Comment by filmor** [comment]
I can confirm that the referenced issue does not occur when we disable the `mono_jit_cleanup` call as part of the `atexit` calls.

**Comment by lostmsu** [comment]
@filmor here are my test results:
- `AppDomain.ProcessExit` and `AppDomain.DomainUnload` are not even called currently, which is a surprise
- critical finalizers are currently invoked, but will not be invoked if we skip `mono_jit_cleanup`. That is concerning.

**Comment by lostmsu** [comment]
@filmor I am getting trouble debugging Linux+Mono combo. Considering `atexit` is still a viable option, I suggest we turn the `mono_jit_cleanup` off. If I could come up with a fix, it would still be a hack and can break with a new Mono or Python version anyway.

**Comment by lostmsu** [comment]
@filmor are you working on this? If not, I can submit a PR.

**Comment by lostmsu** [comment]
Instead, we improved the shutdown procedure in https://github.com/pythonnet/pythonnet/pull/1712
