### ISSUE TITLE
Using a relocated Mono

### ISSUE THREAD

**Issue by tkacvins** [pythonnet/clr-loader#27]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9.2
-   Operating System: CentOS 7
-   .NET Runtime: 4.5

### Details

-   I relocated the `mono` I built from source (in preparation for embedding `mono` in a product) and got this

 ```
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/opt/mono-6.8.0.123/lib/mono/4.5/mscorlib.dll' directory.
```
My understanding is `mono` can be relocated, but it requires invoking their C API to set the assembly paths, etc...
It would be nice if `clr-loader` could enable this by calling the right functions from `libmono-2.so`

I found this problem after relocating `mono` by running

`echo "import clr" | python3`

**Comment by filmor** [comment]
If I see this correctly, this is really just a matter of calling `mono_set_dirs`.

**Comment by tkacvins** [comment]
Agreed, I had determined that using `mono_set_dirs` is what I want to use, but I never had a chance to roll back around to this.
