### ISSUE TITLE
get_coreclr throws exception "TypeError: get_coreclr() takes 0 positional arguments but 1 was given" in version 0.2.3. Works in version 0.1.7

### ISSUE THREAD

**Issue by DareDevilDenis** [pythonnet/clr-loader#35]
The following code works with clr-loader 0.1.7

```python
from clr_loader import get_coreclr

runtime  = get_coreclr('MyApplication.runtimeconfig.json')
print('Success')

```

With clr-loader 0.2.3 it throws exception:

`TypeError: get_coreclr() takes 0 positional arguments but 1 was given`

**Comment by filmor** [comment]
This is intentional: https://github.com/pythonnet/pythonnet/discussions/1837#discussioncomment-3706092

**Comment by DareDevilDenis** [comment]
Ok, thanks for the quick response
