### ISSUE TITLE
Could not find a suitable hostfxr library

### ISSUE THREAD

**Issue by gabloe** [pythonnet/clr-loader#40]
### Environment

-   Pythonnet version: 3.0.0.post1
-   Python version: 3.8
-   Operating System: macOS 12.6
-   .NET Runtime: .NETCore 6
-   Architecture: arm64 (Apple M1)

### Details

```python
import os
import sys
from clr_loader import get_coreclr
from pythonnet import set_runtime

runtime_config = os.path.join("/Users/gabloe/dotnetconfig", "pythonnettest.runtimeconfig.json")
rt = get_coreclr(runtime_config=runtime_config)
set_runtime(rt)

import clr
```

### Traceback
```
Traceback (most recent call last):
...
    rt = get_coreclr(runtime_config=runtime_config)
  File "/Users/gabloe/Library/Caches/pypoetry/virtualenvs/test-lQu4lGUY-py3.8/lib/python3.8/site-packages/clr_loader/__init__.py", line 122, in get_coreclr
    impl = DotnetCoreRuntime(runtime_config=runtime_config, dotnet_root=dotnet_root)
  File "/Users/gabloe/Library/Caches/pypoetry/virtualenvs/test-lQu4lGUY-py3.8/lib/python3.8/site-packages/clr_loader/hostfxr.py", line 20, in __init__
    self._dll = load_hostfxr(self._dotnet_root)
  File "/Users/gabloe/Library/Caches/pypoetry/virtualenvs/test-lQu4lGUY-py3.8/lib/python3.8/site-packages/clr_loader/ffi/__init__.py", line 31, in load_hostfxr
    raise RuntimeError(f"Could not find a suitable hostfxr library in {dotnet_root}")
RuntimeError: Could not find a suitable hostfxr library in /usr/local/share/dotnet
Exception ignored in: <function Runtime.__del__ at 0x7f8609306820>
Traceback (most recent call last):
  File "/Users/gabloe/Library/Caches/pypoetry/virtualenvs/test-lQu4lGUY-py3.8/lib/python3.8/site-packages/clr_loader/types.py", line 137, in __del__
    self.shutdown()
  File "/Users/gabloe/Library/Caches/pypoetry/virtualenvs/test-lQu4lGUY-py3.8/lib/python3.8/site-packages/clr_loader/hostfxr.py", line 111, in shutdown
    if self._handle is not None:
AttributeError: 'DotnetCoreRuntime' object has no attribute '_handle'
```

**Comment by filmor** [comment]
I don't have a mac to check this, but could it be that the issue is along the lines of https://github.com/pythonnet/clr-loader/issues/36, that the `dotnet` path is not looked up correctly? What's the output of `which dotnet` in a terminal?

**Comment by gabloe** [comment]
> I don't have a mac to check this, but could it be that the issue is along the lines of #36, that the `dotnet` path is not looked up correctly? What's the output of `which dotnet` in a terminal?

```
gabloe ~> which dotnet
/usr/local/share/dotnet/dotnet
```

Seems to be correct, at least it is the same path referenced in the exception

**Comment by gabloe** [comment]
Also if it helps, here is the .NET information from my system:
```
 gabloe /usr/local/share/dotnet> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: arm64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]
  6.0.401 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by gabloe** [comment]
Ahh, that is right.  After re-installing python from the universal package it is now working properly. Thanks @filmor.

**Comment by thomasnal** [comment]
It makes sense and gives me the insight.  Thanks.

In my case, I have python architecture arm64, .net architecture arm64, but the host/fxr folder has only these versions:
```
$ ls -l /usr/local/share/dotnet/x64/host/fxr/
total 0
drwxr-xr-x  3 root  wheel  96 16 Jun 00:09 3.1.27
drwxr-xr-x  3 root  wheel  96 26 Sep 21:30 3.1.30
```
I need to find out how to make dotnet install hostfxr 6.10.

**Comment by thomasnal** [comment]
I copied dotnet/host/fxr/6.0.10 to dotnet/x64/host/fxr leading to this error,

You must install or update .NET to run this application.

App: /Users/thomas.nalevajko/.pyenv/versions/3.9.13/bin/python3.9
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '6.0.10' (arm64)
.NET location: /usr/local/share/dotnet/x64

The following frameworks were found:
  3.1.27 at [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]
  3.1.30 at [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]
How can I tell to pythonnet that the correct dotnet path /usr/local/share/dotnet (without x64)?

**Comment by LeeDongGeon1996** [comment]
@filmor Sorry, I also think my previous PR is wrong.. 
To check system architecture correctly, we need the codes below:
```python
if "ARM" in platform.machine().upper():
```
If you don't mind, can I send fixed PR?

**Comment by zarkin404** [comment]
> When I override the dotnet path that pythonnet uses then runtime loads up,
> 
> ```python
> from pythonnet import set_runtime
> from clr_loader import get_coreclr
> 
> rt = get_coreclr(dotnet_root=Path('/usr/local/share/dotnet'))
> set_runtime(rt)
> 
> import clr
> ```

dude, you save my time
