### ISSUE TITLE
The __version__ attribute is not defined

### ISSUE THREAD

**Issue by jorgepiloto** [pythonnet/clr-loader#50]
🐞 **Problem**
The `__version__` attribute is not defined anywhere in the source code. The `dynamic` field is declared in the `pyproject.toml` but there is no version specified in the `__init__.py` top file.

💡 **Idea**
Declare this variable in the `__init__.py` file. Note the value of the `__version__` needs to be updated every time a release is made.

**Comment by jorgepiloto** [comment]
This is related with #44.

**Comment by jorgepiloto** [comment]
Pinging @koubaa.

**Comment by filmor** [comment]
This is not related at all to #44. #44 is about the version that is reported by the framework.

As I noted [https://github.com/pythonnet/pythonnet/issues/1909#issuecomment-1250091669](here), you can just use `importlib.metadata.version` to retrieve the version, I don't see any point in complicating the build process (which your PR doesn't even touch).
