### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by amos402** [pythonnet/clr-loader#6]
https://github.com/pythonnet/clr-loader/blob/e512c7a645dc702ef82f8368d8b526009fd19ebd/netfx_loader/ClrLoader.cs#L32
It's not necessary to use `pinned`, there nowhere used its original structure.

https://github.com/pythonnet/clr-loader/blob/e512c7a645dc702ef82f8368d8b526009fd19ebd/netfx_loader/ClrLoader.cs#L66
`deleg` is a local variable, once the method returned, it might be collected by GC, after that, the pinter is a dangling one.

**Comment by filmor** [comment]
> https://github.com/pythonnet/clr-loader/blob/e512c7a645dc702ef82f8368d8b526009fd19ebd/netfx_loader/ClrLoader.cs#L32
> 
> It's not necessary to use `pinned`, there nowhere used its original structure.
You are right, I'll fix this to return the `GCHandle` pointer directly.

> https://github.com/pythonnet/clr-loader/blob/e512c7a645dc702ef82f8368d8b526009fd19ebd/netfx_loader/ClrLoader.cs#L66
> 
> `deleg` is a local variable, once the method returned, it might be collected by GC, after that, the pinter is a dangling one.
This is correct as well. I'll probably just add a static dictionary of `GCHandle`'s here, or do you have a better idea?

**Comment by amos402** [comment]
Use a dictionary to hold the reference is enough, and it should be cleared after calling CloseAppDomain.

**Comment by filmor** [comment]
Fixed by #7.
